authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'  # для функции include

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<activation_key>/', verify, name='verify')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls, name='panel'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('contact/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'), name='order')
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import now

from django.db.models.signals import post_save
from django.dispatch import receiver


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatar', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст', default=18)

    activation_key = models.CharField(
        max_length=128,
        blank=True
    )

    activation_key_expires = models.DateTimeField(
        default=(now() + timedelta(hours=24))
    )

    @property
    def is_activation_key_expired(self):
        return now() > self.activation_key_expires


class ShopUserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж')
    )

    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)

    tagline = models.CharField(verbose_name='тэги', max_length=128, blank=True)

    about_me = models.TextField(verbose_name='о себе', max_length=512, blank=True)

    gender = models.CharField(verbose_name='пол', max_length=1, choices=GENDER_CHOICES, blank=True)

    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=ShopUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

authapp/forms.py
import hashlib
from uuid import uuid4

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import ShopUser, ShopUserProfile


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        print('ShopUserRegisterForm')
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

    def save(self):
        user = super(ShopUserRegisterForm, self).save()

        user.is_active = False
        salt = uuid4().hex
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        fields = ('tagline', 'about_me', 'gender')

    def __init__(self, *args, **kwargs):
        super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

authapp/views.py
from django.contrib import auth
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm, ShopUserProfileEditForm
from authapp.models import ShopUser
from geekshop import settings


def login(request):
    title = 'вход'
    credentials = {}

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST':
        login_form = ShopUserLoginForm(data=request.POST)
        if login_form.is_valid():
            credentials['username'] = request.POST['username']
            credentials['password'] = request.POST['password']

            user = auth.authenticate(**credentials)
            if user and user.is_active:
                auth.login(request, user)
                if 'next' in request.POST.keys():
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('index'))
    else:
        login_form = ShopUserLoginForm()

    context = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def send_verify_mail(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])

    subject = f'Подтверждение регистрации на сайте {settings.DOMAIN_NAME}'

    message = f'Для подтверждение учетной записи {user.username} на сайте {settings.DOMAIN_NAME}' \
              f' - пройдите по ссылке: {settings.DOMAIN_NAME}{verify_link}'

    html_message = f'<div>Для подтверждение учетной записи {user.username} на сайте {settings.DOMAIN_NAME}' \
                   f' - пройдите по ссылке: <a href="{settings.DOMAIN_NAME}{verify_link}">Активировать</a></div>'

    return send_mail(
        subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False, html_message=html_message
    )


def verify(request, email, activation_key):

    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired:
            user.is_active = True
            user.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return render(request, 'authapp/verification.html')
        else:
            print(f'Activation key error. User: ({user.username})')
            return render(request, 'authapp/verification.html')
    except Exception as error:
        print(f'Error: {error.args}')
        return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        print('******************', register_form.is_valid())
        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print('сообщение отправлено')
                return render(
                    request,
                    'authapp/registration_result.html',
                    {'title': title, 'user': user, 'success': True}
                )
            else:
                print('сообщение не отправлено')
                return render(
                    request,
                    'authapp/registration_result.html',
                    {'title': title, 'user': user, 'success': False}
                )
    else:
        register_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'register_form': register_form
    }
    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.shopuserprofile)

    context = {
        'title': title,
        'edit_form': edit_form,
        'profile_form': profile_form,
    }

    return render(request, 'authapp/edit.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title|title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/lib/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/forms.css' %}">

</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-xl-6">
                <h2 class="h2 text-center my-4 head">Вход в систему</h2>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

    <form class="" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="list-group">
            {{ edit_form.as_ul }}
            {{ profile_form.as_ul }}
        </ul>

        <br>
        <input class="form-control btn btn-primary" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round from-control last">
        <a href="{% url 'index' %}" class="">
            на гравную
        </a>
    </button>
    <div class="user_avatar">
        <img src="/media/{{ user.avatar }}">
    </div>

{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        <ul class="list-group">
            {{ login_form.as_ul }}
        </ul>
        <br>
        <input class="form-control btn btn-primary" type="submit" value="войти">
    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            Зарегистрироваться
        </a>
    </button>
    <button class="btn btn-round form-control">
        <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
            Вход через ВКонтакте
        </a>
    </button>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

    <form class="" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="list-group">
            {{ register_form.as_ul }}
        </ul>

        <br>
        <input class="form-control btn btn-primary" type="submit" value="Зарегистрироваться">
    </form>

{% endblock %}

authapp/templates/authapp/registration_result.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

{% if success %}
    <h3>Поздравляем, регистрация прошла успешно!</h3>
    <br>
    <h4>
        На почтовый яищк {{ user.email }} было отправлено письмо с ссылкой для активации аккаунта.
    </h4>
{% else %}
    <h4>
        При регистрации аккаунта {{ user.username }} произошел сбой.
        Обрартитесь в службу технической поддержки support@geekshop.com
    </h4>
{% endif %}
<br>
<a href="{% url 'index' %}" class="">
    <button class="btn btn-round form-control">
        на главную
    </button>
</a>

{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

{% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
{% else %}
<h3>Верификация не пройдена.</h3>
{% endif %}
<br>
<a href="{% url 'index' %}" class="">
    <button class="btn btn-round form-control">
        на главную
    </button>
</a>

{% endblock %}

authapp/templates/authapp/verififcation.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

{% if user %}
<h3>Поздравляем!</h3>
<br>
<h4>Пользователь {{user.username}} подтвержден.</h4>
{% else %}
<h3>Верификация не пройдена.</h3>
{% endif %}
<br>
<a href="{% url 'index' %}" class="">
    <button class="btn btn-round form-control">
        на главную
    </button>
</a>

{% endblock %}