authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'  # для функции include

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<activation_key>/', verify, name='verify')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls, name='panel'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('contact/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'), name='order')
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp.views import product_list, product_details, product_list_ajax

app_name = 'mainapp'

urlpatterns = [
    path('', product_list, name='index'),
    path('ajax/', product_list, name='ajax'),
    path('category/<int:pk>/', product_list, name='category'),
    path('category/<int:pk>/ajax/', cache_page(3600)(product_list_ajax), name='ajax'),
    path('category/<int:pk>/page/<int:page>/', product_list, name='page'),
    path('category/<int:pk>/page/<int:page>/ajax/', cache_page(3600)(product_list_ajax), name='ajax'),
    path('product/<int:pk>/', product_details, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True
    )
    is_active = models.BooleanField(
        verbose_name='активна',
        default=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.PROTECT,
        verbose_name='категория',
    )
    name = models.CharField(
        verbose_name='имя',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )
    short_desc = models.CharField(
        max_length=256,
        blank=True,
        verbose_name='краткое описание',
    )
    description = models.TextField(
        blank=True,
        verbose_name='описание',
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    qtty = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )
    is_active = models.BooleanField(
        verbose_name='активен',
        default=True
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        print(f'Product Save: ID: {self.pk} QTTY: {self.qtty}')
        super(self.__class__, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    @property
    def split_description(self):
        descriptions = self.description.split(';')
        return list(map(lambda s: s.strip(), descriptions))

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True)

    @staticmethod
    def get_popular_products():
        _items = Product.get_items()
        return list(_items.order_by('price').values())[:3]

    @staticmethod
    def get_new_products():
        _items = Product.get_items()
        return list(_items.order_by('-id').values())[:3]


class Contact(models.Model):
    location = models.CharField(
        verbose_name='населенный пункт',
        max_length=64,
    )
    phone = models.CharField(
        verbose_name='телефон',
        max_length=16,
        blank=True,
    )
    email = models.CharField(
        verbose_name='электронная почта',
        max_length=64,
        blank=True,
    )
    address = models.CharField(
        verbose_name='адрес',
        max_length=256,
        blank=True,
    )

    def __str__(self):
        return self.location

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

mainapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.conf import settings
from django.template.loader import render_to_string

from .models import Product, ProductCategory


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def product_list(request, pk=0, page=1):
    title = 'каталог'
    menu_items = get_links_menu()

    if pk == 0:
        category = {
            'pk': 0,
            'name': 'Все',
        }
        products = get_products()
    else:
        category = get_category(pk)
        products = get_products_in_category_ordered_by_price(pk)

    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'menu_items': menu_items,
        'products': products_paginator,
        'category': category,
    }

    return render(request, 'mainapp/product_list.html', context)


def product_list_ajax(request, pk=0, page=1):
    title = 'каталог'
    menu_items = get_links_menu()

    if pk == 0:
        category = {
            'pk': 0,
            'name': 'Все',
        }
        products = get_products()
    else:
        category = get_category(pk)
        products = get_products_in_category_ordered_by_price(pk)

    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'menu_items': menu_items,
        'products': products_paginator,
        'category': category,
    }

    result = render_to_string(
        'mainapp/includes/inc_product_list_content.html',
        context=context,
        request=request
    )

    return JsonResponse({'result': result})


def product_details(request, pk=None):
    title = 'каталог'

    if pk:
        product = get_product(pk)
        products = list(Product.objects.filter(category_id=product.category)
                        .exclude(pk=pk)
                        .values_list('pk', 'image', 'category__name', 'name', 'short_desc', ))[:3]
    else:
        products = get_products()[:3]
    context = {
        'title': title,
        'products': products,
        'product': product,
    }

    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/_prev_product.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block content %}
	<div class="hero-white">
		{% include 'geekshop/includes/inc_main_menu.html' %}
	</div>

	<div class="details">
		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="{% static 'geekshop/img/slider1.jpg' %}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">Отличный стул</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> 2585.9 <span>руб</span></p>
				<a href="#" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>Расположитесь комфортно.</p>
					<p>Отличное качество материалов
					позволит вам это.</p>
					<p>Различные цвета</p>
					<p>высочайший уровень
					эргономики и прочность.</p>
				</div>
			</div>
		</div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="{% url 'products:index' %}">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">

				{% for product in products %}
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<h3>{{ product.category.name }}</h3>
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ product.name|capfirst }}</h4>
								<p>{{ product.description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}

			</div>
		</div>
	</div>

	<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
	<div class="header">
		<div class="base-container">
			<div class="hero-white">
				{% include 'geekshop/includes/inc_main_menu.html' %}
			</div>
		</div>
	</div>

	<div class="details">
		<div class="base-container">
			<div class="details-products row mb-3">
				<div class="details-slider col-md-6">
					<div class="slider-product">
						<img class="img-fluid" src="{{ product.image|media_folder_products }}">
					</div>
				</div>

				<div class="description col-md-6">
					<h3 class="big-bold">{{ product.name }}</h3>
					<p class="price">{{ product.price }}<span>руб</span></p>
					<a href="{% url 'cart:index' product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{% for desc in product.split_description %}
							<p>{{ desc|capfirst }}</p>
						{% endfor %}
					</div>
				</div>
			</div>

			<div class="container">
				<div class="row my-2">
					<h2 class="col-6">Похожие продукты</h2>
					<a class="col-6 text-end explore" href="{% url 'products:index' %}">
						показать все
						<img src="{% static 'geekshop/img/arrow.png' %}" alt="">
					</a>
				</div>

				<div class="row justify-content-start mb-5 tab-content">

					{% for product_item in products %}

					<div class="block mb-2">
						<a href="{% url 'products:product' product_item.0 %}">
							<img class="img-fluid" src="/media/{{ product_item.1 }}" alt="">
							<div class="text">
								<p>{{ product_item.2 }}</p>
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ product_item.3|capfirst }}</h4>
								<p>{{ product_item.4 }}</p>
							</div>
						</a>
					</div>

					{% endfor %}

				</div>
			</div>
		</div>
	</div>

	<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product_list.html
{% extends 'geekshop/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<div class="header">
    <div class="base-container">
        <div class="hero-white">
            {% include 'geekshop/includes/inc_main_menu.html' %}
        </div>
    </div>
</div>

<section class="main mt-4">
    <div class="base-container main_wrapper">
        {% if request.resolver_match.view_name != 'products:ajax' %}
            {% include 'mainapp/includes/inc_product_list_content.html' %}
        {% endif %}
    </div>
</section>
{% if request.resolver_match.view_name == 'products:ajax' %}
    <script src="{% static 'geekshop/js/products_list.js' %}"></script>
{% endif %}
<div class="clr"></div>


{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block content %}
	<div class="hero-white">
		{% include 'geekshop/includes/inc_main_menu.html' %}
	</div>

	<div class="details">
		{% include 'geekshop/includes/inc_category_menu.html' %}
		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="{% static 'geekshop/img/slider1.jpg' %}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll1.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'geekshop/img/controll2.jpg' %}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">Отличный стул</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> 2585.9 <span>руб</span></p>
				<a href="#" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>Расположитесь комфортно.</p>
					<p>Отличное качество материалов
					позволит вам это.</p>
					<p>Различные цвета</p>
					<p>высочайший уровень
					эргономики и прочность.</p>
				</div>
			</div>
		</div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">

				{% for product in products %}
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<h3>{{ product.category.name }}</h3>
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{ product.name|capfirst }}</h4>
								<p>{{ product.description }}</p>
							</div>
						</a>
					</div>
				{% endfor %}

			</div>
		</div>
	</div>

	<div class="clr"></div>
{% endblock %}