authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'  # для функции include

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<activation_key>/', verify, name='verify')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls, name='panel'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('contact/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'), name='order')
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp.views import product_list, product_details, product_list_ajax

app_name = 'mainapp'

urlpatterns = [
    path('', product_list, name='index'),
    path('ajax/', product_list, name='ajax'),
    path('category/<int:pk>/', product_list, name='category'),
    path('category/<int:pk>/ajax/', cache_page(3600)(product_list_ajax), name='ajax'),
    path('category/<int:pk>/page/<int:page>/', product_list, name='page'),
    path('category/<int:pk>/page/<int:page>/ajax/', cache_page(3600)(product_list_ajax), name='ajax'),
    path('product/<int:pk>/', product_details, name='product'),
]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import (OrdersList, OrderItemsCreate, OrderDelete, OrderItemsUpdate, OrderRead,
                             order_forming_complete, get_price)

app_name = 'ordersapp'

urlpatterns = [
    path('', OrdersList.as_view(), name='orders_list'),
    path('create/', OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='order_delete'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('price/<int:pk>/', get_price, name='get_price'),
]

geekshop/views.py
from django.shortcuts import render

from cartapp.models import Cart
from mainapp.models import Product, Contact


def index(request):
    title = 'магазин'

    context = {
        'title': title,
        'popular_products': Product.get_popular_products(),
        'new_products': Product.get_new_products(),
    }

    return render(request, 'geekshop/index.html', context)


def contacts(request):
    title = 'контакты'
    contact_list = Contact.objects.all()

    context = {
        'title': title,
        'contact_list': contact_list,
    }

    print(request.resolver_match)
    return render(request, 'geekshop/contact.html', context)

geekshop/templates/geekshop/includes/inc_category_menu.html
<div class="links clearfix">

    <ul class="links-menu">
        <li>
            <a
                href="{% url 'products:category' 0 %}"
                class="{% if category.pk == 0 %}active{% endif %} menu_category"
            >
                Все
            </a>
        </li>

        {% for item in menu_items %}
        <li>
            <a
                href="{% url 'products:category' item.id %}"
                class="{% if category.pk == item.id %}active{% endif %} menu_category"
            >
                {{item.name}}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

geekshop/templates/geekshop/includes/inc_footer.html
<div class="base-container">
    <div class="base-footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now 'Y' %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
</div>

geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if title == 'магазин' %}active{% endif %}">домой</a></li>
        <li><a href="{% url 'products:index' %}" class="{% if title == 'каталог' %}active{% endif %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}" class="{% if title == 'контакты' %}active{% endif %}">контакты</a></li>

        <li class="auth">
            {% if user.is_authenticated %}
                <div class="dropdown">
                  <button class="btn btn-white dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user.first_name|default:'Пользователь' }}
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                    <li><a class="dropdown-item inline-block" href="{% url 'auth:edit' %}">Профиль</a></li>
                    <li><a class="dropdown-item inline-block" href="{% url 'ordersapp:orders_list' %}">Заказы</a></li>
                    <li><a class="dropdown-item inline-block" href="{% url 'auth:logout' %}">Выход</a></li>
                      {% if user.is_staff %}
                        <li><hr class="dropdown-divider inline-block"></li>
                        <li><a class="dropdown-item inline-block" href="{% url 'admin_staff:index' %}">Менеджер</a></li>
                        {% if user.is_superuser %}
                            <li><a class="dropdown-item inline-block" href="/admin/">Админ</a></li>
                        {% endif %}
                      {% endif %}
                  </ul>
                </div>
            {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>


    </ul>
    <a href="{% url 'cart:index' %}" class="basket">
        <i class="fa fa-shopping-cart"></i>
        {% if count %}
            <span id="badge_count" class="position-absolute top-0 start-10 translate-middle badge rounded-pill bg-danger">
                {{ count }}
            </span>
        {% endif %}
        {% if total_cost %}
            <span id="badge_cost" class="ms-2 badge text-secondary fs-6 fw-normal cart-price">{{ total_cost }} &#8381; </span>

        {% endif %}
    </a>

</div>