authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'  # для функции include

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<activation_key>/', verify, name='verify')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls, name='panel'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('contact/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'), name='order')
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import path

from ordersapp.views import (OrdersList, OrderItemsCreate, OrderDelete, OrderItemsUpdate, OrderRead,
                             order_forming_complete, get_price)

app_name = 'ordersapp'

urlpatterns = [
    path('', OrdersList.as_view(), name='orders_list'),
    path('create/', OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='order_delete'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('price/<int:pk>/', get_price, name='get_price'),
]

ordersapp/models.py
from django.conf import settings
from django.db import models
from django.utils.functional import cached_property

from mainapp.models import Product


class Order(models.Model):

    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'ID'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PROCEEDED, 'оплачен'),
        (PAID, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    created = models.DateTimeField(
        verbose_name='создан',
        auto_now_add=True,
    )

    updated = models.DateTimeField(
        verbose_name='обновлен',
        auto_now=True,
        choices=ORDER_STATUS_CHOICES,
    )

    status = models.CharField(
        verbose_name='статус',
        max_length=3,
        choices=ORDER_STATUS_CHOICES,
        default=FORMING,
    )

    is_active = models.BooleanField(
        verbose_name='активен',
        default=True,
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: {self.id}'

    @cached_property
    def get_related_cached(self):
        return self.orderitems.select_related()

    def get_total_qtty(self):
        _items = self.get_related_cached
        return sum(list(map(lambda x: x.qtty, _items)))

    def get_total_cost(self):
        _items = self.get_related_cached
        return sum(list(map(lambda x: x.qtty * x.product.price, _items)))

    def get_summary(self):
        _items = self.get_related_cached
        return {
            'total_cost': sum(list(map(lambda x: x.qtty * x.product.price, _items))),
            'total_qtty': sum(list(map(lambda x: x.qtty, _items))),
            'updated': self.updated,
            'created': self.created,
            'items': _items,
        }

    def get_product_type_qtty(self):
        _items = self.get_related_cached
        return len(_items)

    def delete(self):
        _items = self.get_related_cached
        for item in _items:
            item.product.qtty += item.qtty
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):

    order = models.ForeignKey(
        Order,
        related_name='orderitems',
        on_delete=models.CASCADE,
    )

    product = models.ForeignKey(
        Product,
        verbose_name='продукт',
        on_delete=models.CASCADE,
    )

    qtty = models.PositiveIntegerField(
        verbose_name='количество',
        default=1,
    )

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

    def get_product_cost(self):
        return self.product.price * self.qtty

ordersapp/forms.py
from django import forms

from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import F
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from cartapp.models import Cart
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrdersList(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Cart)
def product_qtty_update_save(sender, update_fields, instance, **kwargs):
    if update_fields == 'qtty' or 'product':
        if instance.pk:
            instance.product.qtty = F('qtty') - (instance.qtty - sender.get_item(instance.pk).qtty)
        else:
            instance.product.qtty -= instance.qtty
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Cart)
def product_qtty_update_delete(sender, instance, **kwargs):
    instance.product.qtty = F('qtty') + instance.qtty
    instance.product.save()


class OrderItemsCreate(LoginRequiredMixin, CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            cart_items = Cart.move_items(self.request.user)
            if len(cart_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(cart_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = cart_items[num]['product__pk']
                    form.initial['qtty'] = cart_items[num]['qtty']
                    form.initial['price'] = cart_items[num]['product__price']
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderRead(DetailView):
    model = Order
    template_name = 'ordersapp/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders_list')


class OrderRead(LoginRequiredMixin, DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:orders_list'))


def get_price(request, pk):
    product = get_object_or_404(Product, pk=pk)
    print(product.price)
    if product:
        return JsonResponse({'result': product.price})

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/fonts/font-awesome/css/all.min.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/forms.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/admin.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ordersapp/css/orders.css' %}">
    {% endblock %}

    {% block js %}
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script src="{% static 'ordersapp/js/orders_script.js' %}"></script>
    {% endblock %}
</head>
<body>
<div id="order-wrapper">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}
{% block content %}
<div class="category_delete">
    <div class="h1">Уверены, что хотите удалить?</div>
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="row mt-5">
        <form
                action="{% url 'ordersapp:order_delete' object.pk %}"
                method="post"
        >
            {% csrf_token %}
            <input class="btn btn-outline-danger me-3" type="submit" value="удалить">
            <a
                href="{% url 'ordersapp:orders_list' %}"
                class="btn btn-outline-secondary"
            >
                отмена
            </a>
        </form>
    </div>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}
{% block content %}
{% with object_summary=object.get_summary %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<ul class="basket_list list-group list-group-flush">

    {% for item in object_summary.items %}
        <li class="list-group-item basket_record">
            <div class="row" >
                <div class="col-2">
                    <img
                        src="{{ item.product.image|media_folder_products }}"
                        alt="{{ item.product.short_desc }}"
                        class="img-thumbnail"
                        style="max-height: 160px;"
                    >
                </div>
                <div class="col-auto ps-2 text-left">
                    <span class="category_name">
                    {{ item.product.category.name }}
                    </span>
                    <span class="product_name">{{ item.product.name }}</span>
                    <span class="product_price">
                        {{ item.product.price }}&nbspруб
                    </span>
                    <span class="product_quantitiy">
                        x {{ item.qtty }} шт.
                    </span>
                    <span class="product_cost">
                        = {{ item.get_product_cost }}&nbspруб
                    </span>

                </div>
            </div>
        </li>
    {% endfor %}
</ul>
{% endwith %}
{% include 'ordersapp/includes/inc_order_actions.html' %}
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}
{% block content %}
{% with object_summary=object.get_summary %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="order_form">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <table class="table">
            {{ orderitems.management_form }}
            {% for form in orderitems.forms %}
            {% if forloop.first %}
            <thead>
            <tr>
                {% for field in form.visible_fields %}
                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                    {{ field.label|capfirst }}
                </th>
                {% endfor %}
            </tr>
            </thead>
            {% endif %}
            <tr class="formset_row">
                {% for field in form.visible_fields %}
                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {% if field.name != 'price' %}
                        {% if field.name == 'product' %}
                            {% cache 3600 orderitemform_product field.value %}
                                {{ field }}
                            {% endcache %}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% else %}
                        {% if field.value %}
                            <span id="orderitems-{{forloop.parentloop.counter0}}-price">
                                {{ field.value }}
                            </span> руб
                        {% endif %}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <div>
            <button
                    type="submit"
                    value="сохранить"
                    class="btn btn-outline-primary"
            >
                Сохранить
            </button>
        </div>
        {% endwith %}

        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </form>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}
{% block content %}
<div class="h2 text-center head">
    Ваши заказы,
    {% if user.first_name %}
    {{ user.first_name|title}}
    {% else %}
    Пользователь
    {% endif %}
</div>
<table class="table orders_list">
    <thead>
    <tr>
        <th>ID</th>
        <th>Создан</th>
        <th>Обновлен</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for item in object_list %}
    {% if item.is_active %}
    <tr>
        <td class="td1 orders_list">{{ item.pk }}</td>
        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
        <td>{{ item.get_status_display }}</td>
        <td>
            <a href="{% url 'ordersapp:order_read' item.pk %}">
                посмотреть
            </a>
        </td>
        <td>
            {% if item.status == 'FM' %}
            <a href="{% url 'ordersapp:order_update' item.pk %}">
                редактировать
            </a>
            {% endif %}
        </td>
        <td>
            {% if item.status == 'FM' %}
            <a href="{% url 'ordersapp:order_delete' item.pk %}">
                удалить
            </a>
            {% endif %}
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>
<button class="btn btn-default btn-round">
    <a href="{% url 'index' %}">
        на главную
    </a>
</button>
<button class="btn btn-default btn-round">
    <a href="{% url 'ordersapp:order_create' %}">
        новый
    </a>
</button>
{% endblock %}